### ISSUE TITLE
php ending tag

### ISSUE THREAD

**Issue by mistergraphx** [LennyN95/weboutline#2]
Hi and thanks for your addon. 

For generating the outline of a php file it seems that the closing php tag its necessary …

Do you think it possible to deal with that when we ommit the end php tags in some non mixed php source files ?

**Comment by jennifer-radek** [comment]
related to that: the outline only displays functions until `?>` appears.
For example I have a function returning a string with `?>` inside & this function is the last one listed in the outline, although there are more than 5 other functions after it. 
Please fix this.

**Comment by kevingrabher** [comment]
+1 on the issue of @jennifer-radek 
This makes the plugin almost unusable on a lot of files.
Ending and reopening <?php ?> in mixed code files is common practice on a lot of projects.

**Comment by LennyN95** [comment]
Hey guys,
thank you for using the plugin and your support by pointing out these issues.

@mistergraphx you are right, the closing php tag is required. I know it is common to not end with ?> in php files. But it will not be supported so far.

@jennifer-radek you are also right, the plugin is not able to detect ?> within any context. PHP parsing starts with <?php and ends with ?>. I know that there are lot's of cases which require a more complex approach. But I'm not working on this tiny plugin at the moment. Please feel free to send me a pull request!

@kevingrabher I'm not sure if I got your point. Close and open php code is supported. As well as multiple css style sections and js script tags. 

Again, please remember this plugin is very basic. But I'd be glad to accept any further pull request. Maybe there might be a day, bringing this plugin at a next level.

**Comment by kevingrabher** [comment]
@LennyN95 
Sorry, I found the error on my side!
I used `<?` instead of `<?php` once, and any php function after that was not shown anymore (despite there being a proper `<?php` in code later)
