### ISSUE TITLE
AsciiDoctor support

### ISSUE THREAD

**Issue by john-cj** [LennyN95/weboutline#3]
It will be great to have it. Markdown is good, AsciiDoctor is much better. Here is user manual:

https://asciidoctor.org/docs/user-manual/

**Comment by LennyN95** [comment]
Hey @john-cj, 
thx for your interest! I gave it a quick look. The Plugin is only about outline headers, am I right that in AsciiDoctor headings are mostly equal to headings in Markdown but with = instead of #?
